### ISSUE TITLE
For REST Server - Why not use the provided script rather that 2 kubectl commands

### ISSUE THREAD

**Issue by rthatcher** [IBM-Blockchain/ibm-blockchain.github.io#35]
On this page:
https://ibm-blockchain.github.io/interacting/

Under - 4. Start and Access the Composer REST Server
We are asking users to run 2 kubectl commands.
I think it would be easier and less error prone to use the one line script to create the REST Server (assuming the script still works OK)
The script is:
... /cs-offerings/free/scripts/create/create_composer-rest-server.sh

**Comment by mrshah-at-work** [comment]
Thanks @rthatcher, we can do that too.
