### ISSUE TITLE
Command to run create_composer-rest-server.sh script is wrong

### ISSUE THREAD

**Issue by hancockp-at-ibm** [IBM-Blockchain/ibm-blockchain.github.io#40]
The command given in this section does not work
https://github.com/IBM-Blockchain/ibm-blockchain.github.io/blob/master/_pages/03_Interacting%20with%20your%20blockchain.md#4-start-and-access-the-composer-rest-server

It looks like the script used to rely on a hard-coded business network name somewhere  but now it requires one to be passed in from the command line. 

This also makes the comment above it, about the .yaml file, wrong, since it is no longer set up for a default business network

**Comment by dhyey20** [comment]
@hancockp-at-ibm yes seems like [Pull Request](https://github.com/IBM-Blockchain/ibm-container-service/commit/b63edef0f1ab4fde312c2f66a63bf0d651d689d1) changed that. @sstone1 Can you change the documentation to what is required to be passed?

**Comment by sstone1** [comment]
@hancockp-at-ibm fixed!
