### ISSUE TITLE
Workshop feedback

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/ibm-blockchain.github.io#42]
`devlop` on first page under "IBM Blockchain Production Deployment".

Invalid JSON in the steps for the production deployment with a missing quote around `timeout`.

Steps are wrong way round for "preparing your peers" and creating a connection profile, which requires a channel name - creating a channel before "preparing your peers" means you have to create a new channel.

Under importing a new identity, it says "create a new id".

Describe admin credentials and the powers that they have.

Extend to include deploying a REST server documentation.

**Comment by winslet** [comment]
Now outdated, if needs to be opened please reopen.
