### ISSUE TITLE
Incorrect link to Bluemix CLI instructions

### ISSUE THREAD

**Issue by dwakeman** [IBM-Blockchain/ibm-blockchain.github.io#48]
On the Prepare and Setup page:

https://ibm-blockchain.github.io/setup/

Step two, the link to install Bluemix CLI is wrong;  The link itself is valid, but the link to Bluemix Docs on the linked page is invalid.

I suspect this might be the URL that should point to the instructions to install Bluemix CLI.

https://console.bluemix.net/docs/cli/reference/bluemix_cli/download_cli.html#download_install

**Comment by mrshah-at-work** [comment]
https://github.com/IBM-Blockchain/ibm-blockchain.github.io/pull/51 should fix it.
