### ISSUE TITLE
Command to deploy composer-rest-server fails

### ISSUE THREAD

**Issue by dwakeman** [IBM-Blockchain/ibm-blockchain.github.io#49]
On this page:

https://ibm-blockchain.github.io/interacting/

Step 4, step 1 it has this text as the command to deploy composer-rest-server:

cd cs-offerings/scripts/
 ./create/create_composer-rest-server.sh --business-network-id INSERT_BIZNET_NAME

That failed; I removed the "--business-network-id" and it worked.  When it failed, the composer-rest-server logs showed that it thought "--business-network-id" was the  name of the business network.

**Comment by dhyey20** [comment]
@dwakeman The instructions that you are referring to were updated today to match the new code that was pushed today. That's why you are seeing this issue.

**Comment by dwakeman** [comment]
Ah....  Because I originally cloned the repo for the IBM Container Service a couple of weeks ago I still had the old scripts on my machine.  That was the one thing I forgot to check.

Thanks!!

**Comment by mrshah-at-work** [comment]
I think we should lock the kube-configs to a particular version of the hyperledger-composer version.

Edit: looks like I commented on a wrong issue, sorry!
