### ISSUE TITLE
Incompatible versions of composer between deployed business network and composer-rest-server

### ISSUE THREAD

**Issue by dwakeman** [IBM-Blockchain/ibm-blockchain.github.io#50]
There is an underlying assumption to this document that all of the blockchain components will be deployed to IBM Container Services on the same day.  I ran into a situation where I deployed Fabric and the Composer Playground, and then built and deployed a business network.  Time got away from me and I didn't get around to deploying composer-rest-server until a couple of weeks later.

The Composer Playground container uses composer 0.12.2, which was current on the day I deployed it.  My composer-rest-server container uses composer 0.13.1, which is current as of the day of this post.  As a result my composer-rest-server fails with the "this version of composer is incompatible with the composer runtime" error.  

The only way to know there was even a problem is that I could not connect to the API Explorer.  Perhaps it might help others to include a few instructions for troubleshooting when this happens.  I used `kubectl logs composer-rest-server-xxxxxxxxx` to find the error.  I am not sure what the actual resolution would be, except to delete all of the kubernetes components and start over.

**Comment by mrshah-at-work** [comment]
We should lock the kube-configs to a particular version of the hyperledger-composer version, so it will not pull the latest and won't pull an incompatible version.

**Comment by mrshah-at-work** [comment]
https://github.com/IBM-Blockchain/ibm-container-service/pull/28 should fix this.
