### ISSUE TITLE
Update IBM Blockchain setup docs to reflect new Composer authentication

### ISSUE THREAD

**Issue by ajpauwels** [IBM-Blockchain/ibm-blockchain.github.io#55]
Specifically referring to the bottom of this page:
https://ibm-blockchain.github.io/interacting/

Now that admin/adminpw is exchanged for certs, when Composer REST server is brought up it grabs the certs and stores them, making them unavailable to any CLI command, so commands like ping will fail. New instructions should be added which issue a new admin identity separate from the REST admin identity that can be used with CLI.

**Comment by mrshah-at-work** [comment]
Thanks @ajpauwels. Is this related to https://github.com/IBM-Blockchain/ibm-container-service/issues/10 ?

**Comment by ajpauwels** [comment]
I think so, but I'd need more context to be sure. You could copy the admin certs, or you could let REST server use those certs and issue a separate identity for the CLI.

**Comment by mrshah-at-work** [comment]
@ajpauwels added more context on https://github.com/IBM-Blockchain/ibm-container-service/issues/10, let me know if it helps..

If you generate new admin certs, you will have to install the public keys on the peers (and orderer) to perform admin actions.

**Comment by ajpauwels** [comment]
Copying admin certs with kubectl would work fine, looks like that's the same issue.
