### ISSUE TITLE
Bad link in 'Interacting with your Blockchain' doc

### ISSUE THREAD

**Issue by lesleyannjordan** [IBM-Blockchain/ibm-blockchain.github.io#65]
From page https://ibm-blockchain.github.io/interacting/

Under step 3 link titled _'Hyperledger Composer playground guide'_  points to a url : 

https://hyperledger.github.io/composer/stable/tutorials/playground-guide.html

which reports _'Oh no!…there’s no blockchain here :('_

**Comment by hancockp-at-ibm** [comment]
Also the link in step 4, 'Integrating existing systems documentation', points to 
https://hyperledger.github.io/composer/stable/integrating/integrating-index.html
which does not exists.
Both links point to Hyperledger documentation instead of the IBM Branded version.

**Comment by hancockp-at-ibm** [comment]
the 'paid' version of the page is wrong too.
https://ibm-blockchain.github.io/paid/interacting/

**Comment by davidkel** [comment]
These should all now be pointing to the IBM version of the composer docs, not the open source version. Also due to lack of info in the docs we should also consider referring to this stackoverflow question and answer
https://stackoverflow.com/questions/48191817/deploy-a-business-network-on-bluemix

**Comment by jt-nti** [comment]
Fixed the broken links. Will have a look for somewhere suitable to put the info re: default credentials in the fabric network. Might be best in the Composer doc, e.g. development environment install?

**Comment by jt-nti** [comment]
I think hyperledger/composer#3165 covers the missing doc regarding the network admin credentials

**Comment by winslet** [comment]
Looks to be closed, links now work.
