### ISSUE TITLE
Links are broken on ibmblockchain/develop pages

### ISSUE THREAD

**Issue by mrshah-at-work** [IBM-Blockchain/ibm-blockchain.github.io#74]
The links to download the prereqs is broken on https://ibm-blockchain.github.io/develop/installing/installing-prereqs.html

Can we make sure all the pages on this are still up-to-date.

**Comment by jt-nti** [comment]
The link to the prereq script in the sample curl command should be https://ibm-blockchain.github.io/develop/prereqs-ubuntu.sh

**Comment by winslet** [comment]
@jt-nti how can we make changes to these docs? The repo for the docs lives at https://github.com/IBM-Blockchain/develop im not sure if we want to be forking from the main composer docs (which is what we would be doing if we manually change this stuff im assuming?)

**Comment by jt-nti** [comment]
The issue was fixed in hyperledger/composer#3713 but there has not been a new IBM Composer release since then

**Comment by mrshah-at-work** [comment]
@jt-nti @winslet who is responsible for IBM Composer releases? Can we tag them and get it sorted out?

**Comment by jt-nti** [comment]
Unfortunately the recent update to 0.19.5 did not fix this issue. The command should be...

`curl -O https://ibm-blockchain.github.io/develop/prereqs-ubuntu.sh`

**Comment by mrshah-at-work** [comment]
@jt-nti can you please make a PR to update the documentation. Thank you.
