### ISSUE TITLE
RBC bank feedback on 1.1 Peer Docker container cfg 

### ISSUE THREAD

**Issue by pamandrejko** [IBM-Blockchain/ibm-blockchain.github.io#75]
John Harrison is requesting an update to the 1.1 documentation due to a problem that has surfaced at RBC:
@mrshah, @bmos, @dbshah - Any concerns about us documenting this?

By default, Hyperledger Peer Docker containers use the docker.sock file for communications to create chaincode containers via the /host/var/run mount.  Non-root users
running inside Hyperledger Peer Docker containers MUST be a member of the docker group defined in the native OS (/etc/group). If the non-root user running
inside a Hyperledger Peer Docker container does not have the same group id as the docker group id contained in the native OS /etc/group file then the following error
will occur:
Error: Error endorsing chaincode: rpc error: code = Unknown desc = error starting container: 
Post http://unix.sock/containers/create?name=dev-peer0.org2.example.com-mycc-1.0: dial unix /host/var/run/docker.sock: connect: permission denied

Example:
Listing of /etc/group on native OS that includes the docker group:
docker:x:118

The group id of the docker group is 118.

When starting Hyperledger Peer Docker containers ensure that your docker-compose files have overridden the GROUP_ID and use the group id number
listed in /etc/group.  In this case GROUP_ID should be 118.

In your docker compose yaml files change the environment section of your peer containers by adding:
    - GROUP_ID=118 (in this example)

NOTE: You can override the default user id “fabric” if you like, but the key here is that you MUST override the GROUP_ID value.

As a “brute force” solution you can add the following environment variable overrides to your peer containers:
     - USERNAME=root
     - GROUP_ID=0
     - USER_ID=0

In docker-entrypoint.sh for the orderer and peer containers the following line does not trap stderr messages:
_USER_ID=$(id -u ${USERNAME}) &> /dev/null

If the user does not exist a message is displayed in the log:
id: <username>;  no such user

This can be confusing even though this is working as designed.  If the user does not exist then it will be created
along with its associated username and group attributes.

To suppress the stderr message, I propose using the following line of code for the dockerhub Git Repository (for internal builds):
_USER_ID=$(id -u ${USERNAME} 2> /dev/null)

This will supress the stderr message mentioned above and return a non-zero return code that is checked and acted upon
if a userid is not found, i.e., a new userid will be created (as well as group).

**Comment by pamandrejko** [comment]
From @mrshah-at-ibm 
The processes can be started with the user of choice by passing the following:

    USERNAME=<username of choice>
    GROUP_ID=<guid of choice>
    USER_ID=<uuid of choice>

All the processes will start with the following default user:
USERNAME=fabric
GROUP_ID=198
USER_ID=199

Note: if you are mounting the docker socket inside the peer container, the docker socket will need to have enough permissions for the user to be able to use it. We suggest to pass the docker group's guid to the peer's GRUOUP_ID environment variable.

this needs to be updated in https://github.com/IBM-Blockchain/ibm-blockchain.github.io/blob/master/_pages/09_IBMBlockchain%20Images%20Info.md

**Comment by pamandrejko** [comment]
@mrshah-at-ibm  Could you review the text I added at
https://github.com/pamandrejko/ibm-blockchain.github.io/blob/master/_pages/09_IBMBlockchain%20Images%20Info.md

(I used what you provided with a bit of the information from John). 

Once you are satisfied I'll create a PR.

**Comment by dhyey20** [comment]
The readme has been updated. Thanks @pamandrejko
