### ISSUE TITLE
Update Bluemix CLI to IBM Cloud CLI

### ISSUE THREAD

**Issue by filipecorrea** [IBM-Blockchain/ibm-blockchain.github.io#77]
Update site references from Bluemix CLI to IBM Cloud CLI.

**Comment by filipecorrea** [comment]
I can work on this issue, but I'm not able to change assignees.

**Comment by mrshah-at-work** [comment]
@filipecorrea assigned it to you. Thanks.

**Comment by filipecorrea** [comment]
Thanks, @mrshah-at-ibm.

I wasn't able to create a branch for this issue, but I opened the merge request: https://github.com/IBM-Blockchain/ibm-blockchain.github.io/pull/78

**Comment by sstone1** [comment]
The website has been archived; closing.
