### ISSUE TITLE
Not able to Access the Composer REST Server 

### ISSUE THREAD

**Issue by mdpatankar** [IBM-Blockchain/ibm-blockchain.github.io#80]
After deploying composer rest server on k8s cluster on IBM Cloud, not able to access on the port

**Comment by sstone1** [comment]
@mdpatankar Composer has been removed from these scripts as it no longer works with the latest version of the IBM Container Service; please see https://github.com/IBM-Blockchain/ibm-container-service/issues/120 for details.
